// Code generated by mockery v2.16.0. DO NOT EDIT.

package pkg

import mock "github.com/stretchr/testify/mock"

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

// Ack provides a mock function with given fields: message
func (_m *MockQueue) Ack(message int) {
	_m.Called(message)
}

// Pushback provides a mock function with given fields: message
func (_m *MockQueue) Pushback(message int) {
	_m.Called(message)
}

type mockConstructorTestingTNewMockQueue interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockQueue(t mockConstructorTestingTNewMockQueue) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
