// Code generated by mockery v2.16.0. DO NOT EDIT.

package pkg

import mock "github.com/stretchr/testify/mock"

// MockQueueHandler is an autogenerated mock type for the QueueHandler type
type MockQueueHandler struct {
	mock.Mock
}

// ListenOnTopics provides a mock function with given fields: topicOne
func (_m *MockQueueHandler) ListenOnTopics(topicOne <-chan int) {
	_m.Called(topicOne)
}

type mockConstructorTestingTNewMockQueueHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockQueueHandler creates a new instance of MockQueueHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockQueueHandler(t mockConstructorTestingTNewMockQueueHandler) *MockQueueHandler {
	mock := &MockQueueHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
