// Code generated by mockery v2.16.0. DO NOT EDIT.

package pkg

import mock "github.com/stretchr/testify/mock"

// MockTopicHandler is an autogenerated mock type for the TopicHandler type
type MockTopicHandler struct {
	mock.Mock
}

// ProcssTopic1 provides a mock function with given fields: message
func (_m *MockTopicHandler) ProcssTopic1(message int) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockTopicHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTopicHandler creates a new instance of MockTopicHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTopicHandler(t mockConstructorTestingTNewMockTopicHandler) *MockTopicHandler {
	mock := &MockTopicHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
