// Code generated by mockery v2.16.0. DO NOT EDIT.

package pkg

import mock "github.com/stretchr/testify/mock"

// MockDb is an autogenerated mock type for the Db type
type MockDb struct {
	mock.Mock
}

// Put provides a mock function with given fields: input
func (_m *MockDb) Put(input int) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockDb interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDb creates a new instance of MockDb. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDb(t mockConstructorTestingTNewMockDb) *MockDb {
	mock := &MockDb{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
